#preprod
deployment:
  user: ewallet
  from: ./
  to: /data/apps/leadsfactory-install
  excludes:
    - app/cache
    - app/config
    - app/logs
    - app/sessions
    - datas
  strategy: targz
releases:
  enabled: true
  max: 10
  symlink: ../
  directory: releases
hosts:
  - 10.25.109.230
tasks:
  pre-deploy:
  on-deploy:
    - filesystem/link-shared-files: {linked_folders: [app/cache, app/config, app/logs, app/sessions, datas]}
  post-release:
  post-deploy:
