tellaw_leads_factory_homepage:
    resource: "@TellawLeadsFactoryBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

tellaw_leads_factory_front:
    resource: "@TellawLeadsFactoryBundle/Controller/FrontController.php"
    type:     annotation
    prefix:   /client

tellaw_leads_factory_api:
    resource: "@TellawLeadsFactoryBundle/Controller/ApiController.php"
    type:     annotation
    prefix:   /api

tellaw_leads_factory_twilio:
    resource: "@TellawLeadsFactoryBundle/Controller/TwilioController.php"
    type:     annotation
    prefix:   /twilio

login_check:
    pattern:   /login_check

_security_logout:
    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

#_assetic:
#    resource: .
#    type:     assetic
