<?php

namespace LeadsFactoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LeadsCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadsCommentRepository extends EntityRepository
{

    public function getCommentsForLead($leadId)
    {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('e')
            ->from('TellawLeadsFactoryBundle:LeadsComment', 'e')
            ->where('e.lead_id = :leadId');
        $qb->orderBy('e.created_at', 'DESC');

        $qb->setParameter('leadId', $leadId);

        $query = $qb->getQuery();
        try {
            $result = $query->getResult();
        } catch (\Exception $e) {
            throw new \Exception ($e);
        }

        return $result;

    }

}

