<?php

namespace Tellaw\LeadsFactoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ExportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{

    /**
     * @param $keyword
     * @param int $page
     * @param int $limit
     * @return Paginator
     */
    public function getList($page = 1, $limit = 10, $keyword = '', $params = array())
    {

        $dql = 'SELECT u FROM TellawLeadsFactoryBundle:Users u';

        if (!empty($keyword)) {
            $where = ' WHERE';

            $keywords = explode(' ', $keyword);
            foreach ($keywords as $key => $keyword) {
                if ($key > 0)
                    $where .= ' AND';
                $where .= " u.lastname LIKE '%" . $keyword . "%' OR  u.firstname LIKE '%" . $keyword . "%'";
            }

            if ($params) {
                foreach ($params as $key => $param) {
                    $d_param = $param;
                    if (is_array($param)) $d_param = implode(',', $param);
                    $where .= ' AND u.' . $key . ' IN (' . $d_param . ')';
                }
            }
            $dql .= $where;
        }

        $query = $this->getEntityManager()
            ->createQuery($dql)
            ->setFirstResult(($page - 1) * $limit)
            ->setMaxResults($limit);

        return new Paginator($query);
    }

}
