tellaw_leads_factory_theme:
    resource: "@TellawLeadsFactoryThemeBundle/Controller/"
    type:     annotation
    prefix:   /

weka_leads_export:
    resource: "@WekaLeadsExportBundle/Resources/config/routing.yml"
    prefix:   /

tellaw_leads_factory:
    resource: "@TellawLeadsFactoryBundle/Resources/config/routing.yml"
    prefix:   /

login_path:
    pattern:   /login

login_check:
    pattern:   /login_check

_security_logout:
    pattern:  /logout