tellaw_leads_factory_homepage:
    resource: "@TellawLeadsFactoryBundle/Controller/"
    type:     annotation
    prefix:   /

login_check:
    pattern:   /login_check

_security_logout:
    pattern:  /logout

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

_assetic:
    resource: .
    type:     assetic