parameters:
#    tellaw_leads_factory.example.class: Tellaw\LeadsFactoryBundle\Example

services:

  chart:
    class:        Tellaw\LeadsFactoryBundle\Utils\Chart
    calls:
                  - [ setContainer, [ @service_container ] ]

  export.logger:
    class:        Symfony\Bridge\Monolog\Logger
    arguments:    [app]
    calls:
                  - [pushHandler, [@export.logger_handler]]

  export.logger_handler:
    class:        Monolog\Handler\StreamHandler
    arguments:    [%kernel.logs_dir%/%kernel.environment%.export.log, 200]

  export_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\ExportUtils
    calls:
                  - [ setContainer, [ @service_container ] ]

  csv_method:
    class:        Tellaw\LeadsFactoryBundle\Utils\Export\CSV
    calls:
                  - [ setContainer, [ @service_container ] ]
    tags:
                  - { name: export.method, alias: csv }

  entity_form:
    class:        Tellaw\LeadsFactoryBundle\Form\Type\FormType

  emailFieldType:
    class:        Tellaw\LeadsFactoryBundle\Utils\Fields\EmailFieldType

  form_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\FormUtils
    calls:
                  - [ setContainer, [ @service_container ] ]

  js_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\JsUtils
    calls:
                  - [ setContainer, [ @service_container ] ]