parameters:
#    tellaw_leads_factory.example.class: Tellaw\LeadsFactoryBundle\Example

services:

  export_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\ExportUtils
    calls:
                  - [ setContainer, [ @service_container ] ]

  csv_method:
    class:        Tellaw\LeadsFactoryBundle\Utils\Export\CSV
    calls:
                  - [ setContainer, [ @service_container ] ]
    tags:
                  - { name: export.method, alias: csv }

  entity_form:
    class:        Tellaw\LeadsFactoryBundle\Form\Type\FormType

  emailFieldType:
    class:        Tellaw\LeadsFactoryBundle\Utils\Fields\EmailFieldType

  form_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\FormUtils
    calls:
                  - [ setContainer, [ @service_container ] ]

  js_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\JsUtils
    calls:
                  - [ setContainer, [ @service_container ] ]