parameters:
#    tellaw_leads_factory.example.class: Tellaw\LeadsFactoryBundle\Example

services:
#    tellaw_leads_factory.example:
#        class: %tellaw_leads_factory.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
