parameters:
#    tellaw_leads_factory.example.class: Tellaw\LeadsFactoryBundle\Example

services:

  entity_form:
    class:        Tellaw\LeadsFactoryBundle\Form\Type\FormType

  emailFieldType:
    class:        Tellaw\LeadsFactoryBundle\Utils\Fields\EmailFieldType

  form_utils:
    class:        Tellaw\LeadsFactoryBundle\Utils\FormUtils
    calls:
                  - [ setContainer, [ @service_container ] ]