parameters:
    weka_leads_export.athena.class: Weka\LeadsExportBundle\Utils\Athena
    athena_url: http://athena.host-athena-dev1.captivea.net/index.php
    weka_leads_export.edeal.class: Weka\LeadsExportBundle\Utils\Edeal

services:
    athena_method:
        class: %weka_leads_export.athena.class%
        calls:
          - [setContainer, [@service_container]]
        tags:
          - {name: export.method, alias: athena}
        arguments: [%athena_url%]
    edeal_method:
        class: %weka_leads_export.edeal.class%
        calls:
          - [setContainer, [@service_container]]
        tags:
          - {name: export.method, alias: edeal}
        arguments: [%weka_leads.edeal_credentials%]
