<?php

namespace Tellaw\LeadsFactoryBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * LeadsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeadsRepository extends EntityRepository
{

    public function getList($p=1, $maxPerPage=10)
    {
        $query = $this->getEntityManager()
                    ->createQuery('SELECT l FROM TellawLeadsFactoryBundle:Leads l')
                    ->setFirstResult(($p-1) * $maxPerPage)
                    ->setMaxResults($maxPerPage);

        return new Paginator($query);
    }

}
